name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Build 
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        REACT_APP_TITLE: "Dolly -- Pantahub Device Tools"
        REACT_APP_PH_API_URL: https://api.pantahub.com
        REACT_APP_PH_URL: https://hub.pantacor.com
        REACT_APP_OAUTH_CLIENT_ID: prn:pantahub.com:apis:/cloner
        REACT_APP_OAUTH_DEFAULT_SCOPE: prn:pantahub.com:apis:/base/user.readonly
        REACT_APP_REFRESH_TIME: 5000
        REACT_APP_REDUX_DEBUG: false
      run: |
        npm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
